# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bayesConjRegNormal <- function(n_samp, hyperparameters, Y_, X_) {
    .Call(`_CoarsePosteriorSummary_bayesConjRegNormal`, n_samp, hyperparameters, Y_, X_)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call(`_CoarsePosteriorSummary_rmvnorm`, nsamples, mean, covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call(`_CoarsePosteriorSummary_dmvnorm`, x, mean, covariance)
}

