# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

W2dist_normal <- function(X_, Y_, p) {
    .Call(`_CoarsePosteriorSummary_W2dist_normal`, X_, Y_, p)
}

Wasserstein_p_iid <- function(X_, Y_, p) {
    .Call(`_CoarsePosteriorSummary_Wasserstein_p_iid`, X_, Y_, p)
}

W2_idx <- function(gamma_, X_, theta_, mu_, idx_, max_p) {
    .Call(`_CoarsePosteriorSummary_W2_idx`, gamma_, X_, theta_, mu_, idx_, max_p)
}

bayesConjRegNormal <- function(n_samp, hyperparameters, Y_, X_) {
    .Call(`_CoarsePosteriorSummary_bayesConjRegNormal`, n_samp, hyperparameters, Y_, X_)
}

distance <- function(A_, B_) {
    .Call(`_CoarsePosteriorSummary_distance`, A_, B_)
}

rmvnorm <- function(nsamples, mean, covariance) {
    .Call(`_CoarsePosteriorSummary_rmvnorm`, nsamples, mean, covariance)
}

dmvnorm <- function(x, mean, covariance) {
    .Call(`_CoarsePosteriorSummary_dmvnorm`, x, mean, covariance)
}

mse_C <- function(mu, est) {
    .Call(`_CoarsePosteriorSummary_mse_C`, mu, est)
}

mse_idx_dist <- function(V_, X_, theta_, mu_, idx_, max_p) {
    .Call(`_CoarsePosteriorSummary_mse_idx_dist`, V_, X_, theta_, mu_, idx_, max_p)
}

mse_idx_expect <- function(V_, X_, theta_, mu_, idx_, max_p) {
    .Call(`_CoarsePosteriorSummary_mse_idx_expect`, V_, X_, theta_, mu_, idx_, max_p)
}

mse_idx <- function(V_, X_, mu_, idx_, max_p) {
    .Call(`_CoarsePosteriorSummary_mse_idx`, V_, X_, mu_, idx_, max_p)
}

